/**
 * Theorem-feed audit harness (theorem-discovery v2 T1 — docs/18 §9.5): the ADR-115 log-class
 * audit pattern applied to theorems. Replays real figures — debug-log sessions and saved
 * `.geo.json` fixtures — through `detectTheorems` step by step and reports what surfaced where,
 * so the operator reviews misses/noise IN BULK instead of one live session at a time. Confirmed
 * verdicts then land as ground-truth entries or scenarios: this is how "I'm not happy" turns
 * into labeled data.
 *
 * Pure over inputs (no I/O here); the env-gated spec in `__tests__/theorem-audit.test.ts` does
 * the reading/writing. Feeds are the strict L1/L2 view (no sampled `detectShapes`) — cheap enough
 * to run over hundreds of sessions; the L3 lane gets its own treatment in T4.
 */

import { replay, groupKey } from '../store/geoStore';
import type { Fact } from '../store/geoStore';
import { detectTheorems } from './detect';
import type { TheoremFeedEntry } from './types';

export interface AuditStep {
  utterance: string;
  /** Ids whose attribution is THIS step (the ● new entries) — the step's announcement. */
  newIds: (string | number)[];
  /** The full surfaced feed after this step, in rank order. */
  feed: (string | number)[];
}

export interface AuditedFigure {
  /** Session id / fixture name. */
  source: string;
  steps: AuditStep[];
  /** Ids never surfaced anywhere in the run but present at the end — none by construction; kept for shape parity. */
  finalFeed: (string | number)[];
}

/** Consecutive facts sharing a group = one user step (the fixtures-net convention). */
function stepsOf(facts: Fact[]): { utterance: string; upTo: number }[] {
  const steps: { utterance: string; upTo: number }[] = [];
  for (let i = 0; i < facts.length; i++) {
    const last = steps[steps.length - 1];
    if (last && i > 0 && groupKey(facts[i]) === groupKey(facts[i - 1])) last.upTo = i + 1;
    else steps.push({ utterance: facts[i].utterance ?? '(no utterance)', upTo: i + 1 });
  }
  return steps;
}

/** Trace the theorem feed over one figure's fact list, step by step. */
export function auditFigure(source: string, facts: Fact[]): AuditedFigure {
  const enabled = facts.filter((f) => f.enabled);
  const steps: AuditStep[] = [];
  let feed: TheoremFeedEntry[] = [];
  for (const s of stepsOf(enabled)) {
    const prefix = enabled.slice(0, s.upTo);
    const { construction } = replay(prefix);
    feed = detectTheorems({ facts: prefix, construction });
    steps.push({
      utterance: s.utterance,
      newIds: feed.filter((e) => e.isNew).map((e) => e.id),
      feed: feed.map((e) => e.id),
    });
  }
  return { source, steps, finalFeed: feed.map((e) => e.id) };
}

/** Parse a debug-log JSONL blob into per-session final fact lists (the LAST `figure` event wins). */
export function figuresFromDebugLog(jsonl: string): { session: string; facts: Fact[] }[] {
  const bySession = new Map<string, Fact[]>();
  const order: string[] = [];
  for (const line of jsonl.split('\n')) {
    const s = line.trim();
    if (!s) continue;
    let e: { session?: string; kind?: string; facts?: Fact[] };
    try {
      e = JSON.parse(s) as typeof e;
    } catch {
      continue;
    }
    if (e.kind !== 'figure' || !e.session || !Array.isArray(e.facts)) continue;
    if (!bySession.has(e.session)) order.push(e.session);
    bySession.set(e.session, e.facts);
  }
  return order
    .map((session) => ({ session, facts: bySession.get(session)! }))
    .filter((x) => x.facts.length > 0);
}

/** Render audited figures as the operator's review sheet (markdown). */
export function auditReport(figures: AuditedFigure[]): string {
  const lines: string[] = [
    '# Theorem-feed audit — per-step surfaced ids over real figures',
    '',
    '_Generated by theorem-audit.test.ts (docs/18 §9.5). L1/L2 feed (no sampled shapes)._',
    '_Review for MISSES (a step whose given should announce a theorem but ● is empty) and NOISE_',
    "_(● entries no teacher would surface there). Confirmed verdicts become ground-truth entries._",
    '',
  ];
  for (const f of figures) {
    lines.push(`## ${f.source}`, '');
    for (const s of f.steps) {
      const nu = s.newIds.length ? `● ${s.newIds.join(' ')}` : '—';
      lines.push(`- \`${s.utterance.replace(/`/g, "'")}\` → ${nu}  _(feed: ${s.feed.length})_`);
    }
    lines.push('', `final feed: ${f.finalFeed.join(' ') || '(empty)'}`, '');
  }
  return lines.join('\n');
}
