/**
 * WHAT EACH BUILDER'S PAGE SAYS TO A CRAWLER (#1383, ADR-W-085) — the one table every Vite config
 * passes to `shell/seo/seoPlugin`.
 *
 * Build tooling, like the configs themselves: it is the one place that knows all four products, so
 * `shell/` never has to. Three sources, none of them new judgement:
 *
 *  - **title and description** — the operator-approved wording (#1383, draft v2, ruled 2026-09-24:
 *    Hebrew only, «4 ו-5 יחידות» on all four, «תרגול» and «חינם» kept). Change them only with a ruling;
 *  - **the URL** — `products.json`, so canonical, sitemap and the share store cannot disagree;
 *  - **the examples** — each product's catalog rows marked `featured`, which are the operator's own
 *    choice of what a student is shown first (#1347). A catalog edit updates the page with no edit here.
 *
 * The images (icon, 180 px touch icon, 1200×630 preview) live beside each product's code in `seo/`
 * and are regenerated by `scripts/render-icons.mjs` / `scripts/render-og.mjs`, never edited.
 */
import { readFileSync } from 'node:fs';
import path from 'node:path';
import registry from './products.json';
import type { SeoEntry } from './shell/seo/seoPlugin';
import type { SeoExample } from './shell/seo/seo';
import { COMMAND_CATALOG } from './src/parser/catalog';
import { COMMAND_CATALOG_3D } from './src3d/parser/catalog3';
import { CATALOG as COMPLEX_CATALOG } from './src-complex/parser/catalog';
import { COMMAND_CATALOG_ANALYTIC } from './src-analytic/parser/catalogAnalytic';

export const ORIGIN = 'https://themathbible.com';
const HOME = `${ORIGIN}/`;
const SITE = 'themathbible';
const AUTHOR = { '@type': 'Person', name: 'ד״ר דוד קודיש', url: HOME };

/** The featured rows of a catalog, as the page shows them. */
export function featuredExamples(rows: readonly { he: string; descHe?: string; featured?: true }[]): SeoExample[] {
  return rows.filter((r) => r.featured).map((r) => ({ text: r.he, ...(r.descHe ? { note: r.descHe } : {}) }));
}

type ProductId = '2d' | '3d' | 'complex' | 'analytic';
const products = registry.products as { id: string; url?: string; label?: string }[];
/** The production URL of a builder, from the registry — absolute, trailing slash. */
export function productUrl(id: ProductId): string {
  const p = products.find((x) => x.id === id);
  if (!p?.url) throw new Error(`seo: products.json has no url for "${id}"`);
  return `${ORIGIN}${p.url}`;
}

/** What each builder is called, for its own heading and the others' links. */
const NAMES: Record<ProductId, string> = {
  '2d': 'הנדסת המישור',
  '3d': 'הנדסת המרחב',
  complex: 'מספרים מרוכבים',
  analytic: 'גאומטריה אנליטית',
};

interface Copy {
  id: ProductId;
  entry: string;
  dir: string;
  title: string;
  description: string;
  howTo: string[];
  examples: SeoExample[];
}

/** Steps true of every builder; a product adds its own only where they are true of it alone. */
const TYPE_A_LINE = 'כותבים נתון אחד בכל שורה, כמו בשאלה.';
const IT_BUILDS = 'השרטוט נבנה ומתעדכן עם כל נתון שמוסיפים.';
const KEEP_IT = 'שומרים, משתפים בקישור או מורידים כתמונה.';

const COPY: Copy[] = [
  {
    id: '2d',
    entry: 'index.html',
    dir: 'src',
    title: 'שרטוט גאומטרי אונליין — הנדסת המישור לבגרות במתמטיקה',
    description:
      'בונים שרטוט גיאומטרי מתיאור בעברית: משולשים, מרובעים, מעגלים, תיכונים וחוצי זוויות — «ריבוע ABCD», «נקודה G על AD» — והשרטוט נבנה צעד אחר צעד. חינם, לבגרות 4 ו-5 יחידות.',
    howTo: [TYPE_A_LINE, IT_BUILDS, 'כשיש יותר משרטוט נכון אחד — לוחצים ועוברים לתצורה אחרת.', KEEP_IT],
    examples: featuredExamples(COMMAND_CATALOG),
  },
  {
    id: '3d',
    entry: '3d.html',
    dir: 'src3d',
    title: 'הנדסת המרחב וּוקטורים — שרטוט תלת־ממד לבגרות במתמטיקה',
    description:
      'שרטוט גופים במרחב מתיאור בעברית: קובייה, תיבה ומנסרה על מסך שאפשר לסובב, עם נקודות, וקטורים ובדיקת תשובות וקטוריות מול הציור. חינם, לבגרות 4 ו-5 יחידות.',
    howTo: [TYPE_A_LINE, IT_BUILDS, 'מסובבים את הגוף כדי לראות אותו מכל צד.', KEEP_IT],
    examples: featuredExamples(COMMAND_CATALOG_3D),
  },
  {
    id: 'complex',
    entry: 'complex.html',
    dir: 'src-complex',
    title: 'מספרים מרוכבים — שרטוט במישור גאוס לבגרות במתמטיקה',
    description:
      'מקלידים את נתוני השאלה והם מופיעים במישור גאוס: הצגה קוטבית וקרטזית, שורשי משוואות, ערך מוחלט וארגומנט. תרגול מספרים מרוכבים חינם, לבגרות 4 ו-5 יחידות.',
    howTo: [TYPE_A_LINE, 'כל מספר מופיע כנקודה במישור גאוס, ומספר שמחושב מאחרים זז איתם.', KEEP_IT],
    examples: featuredExamples(COMPLEX_CATALOG),
  },
  {
    id: 'analytic',
    entry: 'analytic.html',
    dir: 'src-analytic',
    title: 'גאומטריה אנליטית — שרטוט במערכת צירים לבגרות',
    description:
      'מקלידים את נתוני השאלה והכלי משרטט במערכת צירים: ישרים, מעגלים, פרבולות ואליפסות, שיפועים ומרחקים. תרגול גיאומטריה אנליטית חינם, לבגרות 4 ו-5 יחידות.',
    howTo: [TYPE_A_LINE, 'כל מה שהנתונים קובעים — נקודות, ישרים, מעגלים — מופיע על הציור.', KEEP_IT],
    examples: featuredExamples(COMMAND_CATALOG_ANALYTIC),
  },
];

const ROOT = path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1'));
const asset = (dir: string, f: string) => path.join(ROOT, dir, 'seo', f);
const optional = (p: string) => {
  try {
    return readFileSync(p);
  } catch {
    return undefined;
  }
};

/** The table the plugin takes: entry HTML file → its page and assets. */
export function seoPages(): Record<string, SeoEntry> {
  const out: Record<string, SeoEntry> = {};
  for (const c of COPY) {
    const url = productUrl(c.id);
    const og = optional(asset(c.dir, 'og.png'));
    out[c.entry] = {
      page: {
        url,
        // The approved wording EXACTLY — no «| themathbible» suffix: v2 dropped it, and it would push
        // every title past the ~60 characters Google shows. `og:site_name` carries the site instead.
        title: c.title,
        description: c.description,
        siteName: SITE,
        name: NAMES[c.id],
        howToHeading: 'איך זה עובד',
        howTo: c.howTo,
        examplesHeading: 'דוגמאות למה אפשר לכתוב',
        examples: c.examples,
        linksHeading: 'עוד כלים',
        links: [
          ...COPY.filter((o) => o.id !== c.id).map((o) => ({ href: productUrl(o.id), label: NAMES[o.id] })),
          { href: HOME, label: 'themathbible.com — כל הכלים והחוברות' },
        ],
        footer: 'חינם, בלי הרשמה · ד״ר דוד קודיש',
        loading: 'הכלי נטען…',
        jsonLd: [
          {
            '@context': 'https://schema.org',
            '@type': 'WebApplication',
            name: NAMES[c.id],
            url,
            description: c.description,
            inLanguage: 'he',
            applicationCategory: 'EducationalApplication',
            operatingSystem: 'Any',
            browserRequirements: 'Requires JavaScript',
            isAccessibleForFree: true,
            offers: { '@type': 'Offer', price: '0', priceCurrency: 'ILS' },
            educationalLevel: 'בגרות במתמטיקה — 4 ו-5 יחידות',
            audience: { '@type': 'EducationalAudience', educationalRole: 'student' },
            author: AUTHOR,
            ...(og ? { image: `${url}seo/og.png` } : {}),
          },
        ],
      },
      assets: {
        iconSvg: readFileSync(asset(c.dir, 'icon.svg'), 'utf8'),
        touchPng: readFileSync(asset(c.dir, 'apple-touch-icon.png')),
        ...(og ? { ogPng: og } : {}),
      },
    };
  }
  return out;
}
