/**
 * Command catalog (Phase 4/5) — the user-facing command reference *and* the
 * coverage map of the engine's vocabulary.
 *
 * One entry per construct, grouped by `category`, each marked `supported` (wired
 * now — clickable to try) or not (planned; `phase` says which sub-phase delivers
 * it). The in-app panel renders this grouped, with a ✓/○ badge, so both a
 * student and the author can see at a glance what works and what's coming.
 *
 * Single source of truth — keep it in step with the rules in `parse.ts` and the
 * engine vocabulary. Flip `supported` to true (and drop `phase`) when a construct
 * lands; the panel updates itself.
 */

export type Category = 'shapes' | 'points' | 'lines' | 'constraints' | 'circles';

export interface CommandDoc {
  /** Example utterance (English) and (Hebrew). */
  en: string;
  he: string;
  /** One-line description, English and Hebrew. */
  descEn: string;
  descHe: string;
  /** Which group it appears under. */
  category: Category;
  /** False = planned but not built yet (engine can't represent it). */
  supported: boolean;
  /** For unbuilt items: the sub-phase that delivers it (e.g. '5b'), shown as a tag. */
  phase?: string;
}

/** Display order + bilingual heading for each category. */
export const CATEGORY_ORDER: Category[] = ['shapes', 'points', 'lines', 'constraints', 'circles'];
export const CATEGORY_LABELS: Record<Category, { en: string; he: string }> = {
  shapes: { en: 'Shapes', he: 'צורות' },
  points: { en: 'Points', he: 'נקודות' },
  lines: { en: 'Lines & perpendiculars', he: 'ישרים ואנכים' },
  constraints: { en: 'Constraints', he: 'אילוצים' },
  circles: { en: 'Circles', he: 'מעגלים' },
};

export const COMMAND_CATALOG: CommandDoc[] = [
  // ── Shapes ──────────────────────────────────────────────────────────────
  { category: 'shapes', supported: true, en: 'triangle ABC', he: 'משולש ABC', descEn: 'A triangle (3 free vertices). Shorthand: △ABC (△ button).', descHe: 'משולש (3 קודקודים חופשיים). קיצור: △ABC (כפתור △).' },
  { category: 'shapes', supported: true, en: 'right triangle ABC', he: 'משולש ישר-זווית ABC', descEn: 'A right triangle (right angle at the last vertex).', descHe: 'משולש ישר-זווית (הזווית הישרה בקודקוד האחרון).' },
  { category: 'shapes', supported: true, en: 'square ABCD', he: 'ריבוע ABCD', descEn: 'A square.', descHe: 'ריבוע.' },
  { category: 'shapes', supported: true, en: 'rectangle ABCD', he: 'מלבן ABCD', descEn: 'A rectangle.', descHe: 'מלבן.' },
  { category: 'shapes', supported: true, en: 'rhombus ABCD', he: 'מעוין ABCD', descEn: 'A rhombus (4 equal sides).', descHe: 'מעוין (4 צלעות שוות).' },
  { category: 'shapes', supported: true, en: 'parallelogram ABCD', he: 'מקבילית ABCD', descEn: 'A parallelogram.', descHe: 'מקבילית.' },
  { category: 'shapes', supported: true, en: 'trapezoid ABCD', he: 'טרפז ABCD', descEn: 'A trapezoid (one pair of parallel sides).', descHe: 'טרפז (זוג צלעות מקבילות).' },
  { category: 'shapes', supported: true, en: 'quadrilateral ABCD', he: 'מרובע ABCD', descEn: 'A general quadrilateral.', descHe: 'מרובע כללי.' },
  { category: 'shapes', supported: true, en: 'kite ABCD', he: 'דלתון ABCD', descEn: 'A kite — two pairs of equal adjacent sides (|AB|=|AD|, |CB|=|CD|).', descHe: 'דלתון — שני זוגות של צלעות סמוכות שוות (|AB|=|AD|, |CB|=|CD|).' },
  { category: 'shapes', supported: true, en: 'isosceles triangle ABC', he: 'משולש שווה שוקיים ABC', descEn: 'An isosceles triangle (|AB|=|AC|, apex A).', descHe: 'משולש שווה שוקיים (|AB|=|AC|, ראש A).' },
  { category: 'shapes', supported: true, en: 'isosceles triangle ABC (AB=AC)', he: 'ABC משולש שווה שוקיים (AB=AC)', descEn: 'A shape with its property in parentheses — the stated pair pins which sides are the legs.', descHe: 'צורה עם התכונה שלה בסוגריים — הזוג שנכתב קובע אילו צלעות הן השוקיים.' },
  { category: 'shapes', supported: true, en: 'square ABCD whose side is 1', he: 'ריבוע ABCD שצלעו הוא 1', descEn: 'A shape declared with its side length in one line (square / rhombus / equilateral triangle).', descHe: 'צורה שמוצהרת יחד עם אורך צלעה בשורה אחת (ריבוע / מעוין / משולש שווה צלעות).' },
  { category: 'shapes', supported: true, en: 'equilateral triangle ABC', he: 'משולש שווה צלעות ABC', descEn: 'An equilateral triangle (all sides equal).', descHe: 'משולש שווה צלעות (כל הצלעות שוות).' },
  { category: 'shapes', supported: true, en: 'isosceles trapezoid ABCD', he: 'טרפז שווה שוקיים ABCD', descEn: 'An isosceles trapezoid (AB∥DC, equal legs |AD|=|BC|).', descHe: 'טרפז שווה שוקיים (AB∥DC, שוקיים שוות |AD|=|BC|).' },
  { category: 'shapes', supported: true, en: 'right trapezoid ABCD', he: 'טרפז ישר-זווית ABCD', descEn: 'A right trapezoid (AB∥DC, a leg ⟂ the bases — right angles at A and D).', descHe: 'טרפז ישר-זווית (AB∥DC, שוק מאונך לבסיסים — זוויות ישרות ב-A וב-D).' },
  { category: 'shapes', supported: true, en: 'regular pentagon ABCDE', he: 'מחומש משוכלל ABCDE', descEn: 'A regular polygon — equal sides and angles (pentagon/hexagon/…).', descHe: 'מצולע משוכלל — צלעות וזוויות שוות (מחומש/משושה/…).' },
  { category: 'shapes', supported: true, en: 'rhombus BDEF inscribed in triangle ABC', he: 'מעוין BDEF חסום במשולש ABC', descEn: 'A rhombus inscribed in a triangle — its vertices ride the sides (a shared label sits at that vertex). "Show another configuration" cycles the mirror.', descHe: 'מעוין חסום במשולש — קודקודיו על הצלעות (אות משותפת יושבת על אותו קודקוד). "הצג תצורה אחרת" מחליף לתמונת הראי.' },
  { category: 'shapes', supported: true, en: 'rectangle DEFG inscribed in triangle ABC', he: 'מלבן DEFG חסום במשולש ABC', descEn: 'A rectangle inscribed in a triangle (base on a side, two vertices on the others — a 1-parameter family). "Show another configuration" cycles which side is the base.', descHe: 'מלבן חסום במשולש (בסיס על צלע, שני קודקודים על האחרות — משפחת מלבנים). "הצג תצורה אחרת" מחליף את צלע הבסיס.' },
  { category: 'shapes', supported: true, en: 'square DEFG inscribed in triangle ABC', he: 'ריבוע DEFG חסום במשולש ABC', descEn: 'A square inscribed in a triangle (base on a side). "Show another configuration" cycles the base side.', descHe: 'ריבוע חסום במשולש (בסיס על צלע). "הצג תצורה אחרת" מחליף את צלע הבסיס.' },

  // ── Points ──────────────────────────────────────────────────────────────
  { category: 'points', supported: true, en: 'point A', he: 'נקודה A', descEn: 'A bare free point (2 DOF), placed in general position and positioned by the next statement.', descHe: 'נקודה חופשית (2 דרגות חופש), ממוקמת לפי המשפט הבא.' },
  { category: 'points', supported: true, en: 'point A at (0,0)', he: 'נקודה A ב-(0,0)', descEn: 'A free point at coordinates.', descHe: 'נקודה חופשית בקואורדינטות.' },
  { category: 'points', supported: true, en: 'point E on AC at 40%', he: 'נקודה E על AC ב-40%', descEn: 'A point on a segment (ratio optional).', descHe: 'נקודה על קטע (יחס לא חובה).' },
  { category: 'points', supported: true, en: 'points F, G, H on AB, AC, CB', he: 'נקודות F, G, H על AB, AC, CB', descEn: 'Several points, each on its own side/line (paired in order).', descHe: 'כמה נקודות, כל אחת על הצלע/הישר שלה (בהתאמה לפי הסדר).' },
  { category: 'points', supported: true, en: 'C is 5 from A and 5 from B', he: 'C במרחק 5 מ-A ו-5 מ-B', descEn: 'A point at given distances from two points.', descHe: 'נקודה במרחקים נתונים משתי נקודות.' },
  { category: 'points', supported: true, en: 'M is the intersection of AC and BD', he: 'M חיתוך AC ו-BD', descEn: 'Where two lines cross (or click the dot on a crossing).', descHe: 'נקודת חיתוך של שני ישרים (או לחיצה על הסימון בהצטלבות).' },
  { category: 'points', supported: true, en: 'G is the intersection of the diagonals of quadrilateral ABCD', he: 'G מפגש האלכסונים במרובע ABCD', descEn: 'The crossing of a quad’s diagonals (by name — no need to spell the pairs).', descHe: 'נקודת מפגש אלכסוני המרובע (לפי שם — בלי לפרט את הזוגות).' },
  { category: 'points', supported: true, en: 'M is the intersection of the medians of triangle ABC', he: 'M מפגש התיכונים במשולש ABC', descEn: 'The centroid — where the three medians meet.', descHe: 'מרכז הכובד — מפגש התיכונים.' },
  { category: 'points', supported: true, en: 'O is the intersection of the angle bisectors of triangle ABC', he: 'O מפגש חוצי הזוויות במשולש ABC', descEn: 'The incentre — where the angle bisectors meet.', descHe: 'מרכז המעגל החסום — מפגש חוצי הזוויות.' },
  { category: 'points', supported: true, en: 'H is the intersection of the altitudes of triangle ABC', he: 'H מפגש הגבהים במשולש ABC', descEn: 'The orthocentre — where the altitudes meet.', descHe: 'מפגש הגבהים.' },
  { category: 'points', supported: true, en: 'P is the intersection of the perpendicular bisectors of triangle ABC', he: 'P מפגש האנכים האמצעיים במשולש ABC', descEn: 'The circumcentre — where the perpendicular bisectors meet.', descHe: 'מרכז המעגל החוסם — מפגש האנכים האמצעיים.' },
  { category: 'points', supported: true, en: 'M is the midpoint of AB', he: 'M אמצע AB', descEn: 'The midpoint of a segment.', descHe: 'אמצע הקטע.' },
  { category: 'points', supported: true, en: 'point F on the extension of AD', he: 'נקודה F על המשך AD', descEn: 'A point beyond a segment, on its ray.', descHe: 'נקודה על המשך הקטע (מעבר לקצה).' },
  { category: 'points', supported: true, en: 'point E lies inside triangle KAO', he: 'הנקודה E נמצאת בתוך המשולש KAO', descEn: 'A point kept inside (or outside) a polygon region. Combines with a carrier: "E is on circle O inside triangle KAO" keeps E on the circle AND inside the triangle.', descHe: 'נקודה שנשארת בתוך (או מחוץ ל) צורה. משתלב עם נשא: "הנקודה E נמצאת על מעגל O בתוך המשולש KAO" — גם על המעגל וגם בתוך המשולש.' },

  // ── Lines & perpendiculars ──────────────────────────────────────────────
  { category: 'lines', supported: true, en: 'segment AC', he: 'קטע AC', descEn: 'Connect two points — or just type "AC" / "line AC" / "קו AC".', descHe: 'חיבור שתי נקודות — או פשוט "AC" / "ישר AC" / "קו AC".' },
  { category: 'lines', supported: true, en: 'a line with point A', he: 'קו ועליו נקודה A', descEn: 'An unnamed line with a point riding it — a first stroke. Later, "point G on the line" puts G on the figure\'s single drawn line.', descHe: 'קו ללא שם ועליו נקודה — פתיחת סרטוט. בהמשך, "נקודה G על הקו" מציבה את G על הקו היחיד שבסרטוט.' },
  { category: 'lines', supported: true, en: 'BC parallel to AD', he: 'BC מקביל ל-AD', descEn: 'Make two segments parallel (drives a sliding point, else checks).', descHe: 'הקבלת שני קטעים (מזיז נקודה שיכולה לזוז, אחרת נבדק).' },
  { category: 'lines', supported: true, en: 'F is the foot of the perpendicular from C to AD', he: 'F רגל האנך מ-C ל-AD', descEn: 'The foot of a perpendicular dropped onto a line.', descHe: 'רגל אנך המורד אל ישר.' },
  { category: 'lines', supported: true, en: 'E is where the bisectors of BAC and BCA meet', he: 'E חיתוך חוצי הזוויות BAC ו-BCA', descEn: 'The point where two angle bisectors cross.', descHe: 'הנקודה שבה נחתכים שני חוצי זווית.' },
  { category: 'lines', supported: true, en: 'bisector of angle ABC', he: 'חוצה זווית ABC', descEn: 'Draw an angle bisector.', descHe: 'ציור חוצה זווית.' },
  { category: 'lines', supported: true, en: 'line through P perpendicular to AB', he: 'ישר דרך P מאונך ל-AB', descEn: 'A perpendicular line through a point.', descHe: 'ישר מאונך דרך נקודה.' },
  { category: 'lines', supported: true, en: 'line through P parallel to AB', he: 'ישר דרך P מקביל ל-AB', descEn: 'A parallel line through a point.', descHe: 'ישר מקביל דרך נקודה.' },
  { category: 'lines', supported: true, en: 'E on line AC', he: 'E על הישר AC', descEn: 'Put a point on the line through two others (a movable point slides onto it; also: line CE passes through A).', descHe: 'הצבת נקודה על הישר העובר דרך שתי נקודות (נקודה שיכולה לזוז מחליקה עד שהיא עליו; גם: הישר CE עובר דרך A).' },
  { category: 'lines', supported: true, en: 'line ABE', he: 'ישר ABE', descEn: 'Three or more points collinear AND in the named order (B between A and E) — the order picks the side.', descHe: 'שלוש נקודות או יותר על ישר אחד ולפי הסדר שנכתב (B בין A ל-E) — הסדר קובע את הצד.' },
  { category: 'lines', supported: true, en: 'median from A in ABC', he: 'תיכון מ-A במשולש ABC', descEn: 'A median (to the opposite midpoint).', descHe: 'תיכון (לאמצע הצלע שממול).' },
  { category: 'lines', supported: true, en: 'AD median to BC', he: 'AD תיכון לצלע BC', descEn: 'A median you name (D = midpoint of BC).', descHe: 'תיכון בשם שתבחרו (D = אמצע BC).' },
  { category: 'lines', supported: true, en: 'height from A in ABC', he: 'גובה מ-A במשולש ABC', descEn: 'An altitude and its foot.', descHe: 'גובה והרגל שלו.' },
  { category: 'lines', supported: true, en: 'perpendicular bisector of AB', he: 'אנך אמצעי ל-AB', descEn: 'The perpendicular bisector of a segment.', descHe: 'האנך האמצעי של הקטע.' },
  { category: 'lines', supported: true, en: 'midsegment to BC in triangle ABC', he: 'קטע האמצעים לצלע BC במשולש ABC', descEn: 'The triangle midsegment — joins the midpoints of the two sides meeting at the apex.', descHe: 'קטע האמצעים במשולש — מחבר את אמצעי שתי הצלעות הנפגשות בקודקוד שממול.' },
  { category: 'lines', supported: true, en: 'midsegment of trapezoid ABCD', he: 'קטע האמצעים בטרפז ABCD', descEn: 'The trapezoid median — joins the midpoints of the two legs, parallel to and midway between the bases.', descHe: 'קטע האמצעים בטרפז — מחבר את אמצעי שתי השוקיים, מקביל לשני הבסיסים ובאמצע ביניהם.' },
  { category: 'lines', supported: true, en: 'AD bisects angle BAC', he: 'AD חוצה את הזווית BAC', descEn: 'An angle bisector that places a point on the opposite side.', descHe: 'חוצה זווית הממקם נקודה על הצלע שממול.' },

  // ── Constraints ─────────────────────────────────────────────────────────
  { category: 'constraints', supported: true, en: 'angle GBA = 37', he: 'זווית GBA = 37', descEn: 'Set an angle — a point that can slide moves to satisfy it; otherwise it is checked.', descHe: 'קביעת זווית — נקודה שיכולה לזוז תוזז כדי לקיימה; אחרת היא נבדקת.' },
  { category: 'constraints', supported: true, en: 'angle ABC equals thirty degrees', he: 'זווית ABC שווה לשלושים מעלות', descEn: 'An angle value written in words — "equals thirty degrees", "forty-five degrees" — reads like the digits.', descHe: 'ערך זווית במילים — "שווה לשלושים מעלות", "ארבעים וחמש מעלות" — נקרא כמו הספרות.' },
  { category: 'constraints', supported: true, en: 'angle AEB equals angle BEC equals 60 degrees', he: 'זוית AEB שווה לזווית BEC שווה 60 מעלות', descEn: 'A chained angle equality with a value — every angle in the chain gets the value (word or = spelling).', descHe: 'שרשרת שוויון זוויות עם ערך — כל זווית בשרשרת מקבלת את הערך (במילים או ב-=).' },
  { category: 'constraints', supported: true, en: 'arc DE = 2 arc CE in circle O', he: 'קשת DE = 2 קשת CE במעגל O', descEn: 'An arc-measure relation on the circle (an arc equals its central angle). Drives a point to satisfy it, else checks.', descHe: 'יחס בין קשתות במעגל (מידת קשת = הזווית המרכזית שלה). מזיז נקודה כדי לקיימו, אחרת נבדק.' },
  { category: 'constraints', supported: true, en: 'arc AB = 40 in circle O', he: 'קשת AB = 40 במעגל O', descEn: 'An arc\'s MEASURE in degrees (= its central angle; also the ⌢{} button: ⌢{AB} = 40). Drives a free on-circle point, else checks.', descHe: 'מידת קשת במעלות (= הזווית המרכזית שלה; גם בכפתור ⌢{}: ⌢{AB} = 40). מזיז נקודה חופשית על המעגל, אחרת נבדק.' },
  { category: 'constraints', supported: true, en: 'arc AC + arc BE = arc AD + arc BC in circle O', he: 'קשת AC + קשת BE = קשת AD + קשת BC במעגל O', descEn: 'A SUM of measures as a given — arcs (as central angles), segment lengths ("AB + CD = EF") or angles ("angle ABC + angle DEF = 180"), with coefficients ("2·AB = CD + EF"). Drives a free point so the sum holds, else checks.', descHe: 'סכום של מידות כנתון — קשתות (כזוויות מרכזיות), אורכי קטעים ("AB + CD = EF") או זוויות ("זווית ABC + זווית DEF = 180"), גם עם מקדמים ("2·AB = CD + EF"). מזיז נקודה חופשית כדי שהסכום יתקיים, אחרת נבדק.' },
  { category: 'constraints', supported: true, en: 'DM*ME = BM*DR', he: 'DM*ME = BM*DR', descEn: 'A product/proportion between segment lengths (power-of-a-point form): also "DM/ME = BM/DM" and squares "4*DM^2 = BM*ME" (same number of segments on each side). Drives a free point, else checks.', descHe: 'מכפלה/פרופורציה בין אורכי קטעים (צורת חזקת הנקודה): גם "DM/ME = BM/DM" וריבועים "4*DM^2 = BM*ME" (אותו מספר קטעים בכל אגף). מזיז נקודה חופשית, אחרת נבדק.' },
  { category: 'constraints', supported: true, en: 'central angle COD', he: 'זוית מרכזית COD', descEn: 'The angle at the circle\'s centre O between radii to on-circle points C, D (also "central angle subtending arc CD"). With a value ("= 80") it is an angle given; valueless it marks the angle.', descHe: 'הזווית במרכז המעגל O בין הרדיוסים לנקודות C, D שעל המעגל (גם "זוית מרכזית נשענת על קשת CD"). עם ערך ("= 80") זהו נתון זווית; ללא ערך הזווית מסומנת.' },
  { category: 'constraints', supported: true, en: 'S_{ABC} = 13', he: 'שטח המשולש ABC הוא 13', descEn: 'A polygon\'s area — type S_{ABC} (S_{} button), S_ABC, or SABC; verbose "area of triangle ABC = 13" too. A lone area sets the figure\'s scale; with another given it shapes it.', descHe: 'שטח של מצולע — אפשר S_{ABC} (כפתור S_{}), S_ABC, או SABC; גם מילולית "שטח המשולש ABC הוא 13". שטח בודד קובע את גודל הסרטוט; עם נתון נוסף הוא קובע גם את הצורה.' },
  { category: 'constraints', supported: true, en: 'S_{ABC}/S_{DEF} = 3/4', he: 'שטח ABF גדול פי 2 משטח BFE', descEn: 'A ratio between two polygon areas (also "area ABF = 2 area BFE", "a quarter of"). Reshapes the figure to satisfy it.', descHe: 'יחס בין שטחי שני מצולעים (גם "גדול פי 2 מ", "רבע מ"). משנה את הצורה כדי לקיימו.' },
  { category: 'constraints', supported: true, en: 'S_{ABC} = S', he: 'נסמן את שטח ABCD ב-S', descEn: 'Label a polygon\'s area with a letter; share it (e.g. S_{DEF} = S) to relate two areas.', descHe: 'סימון שטח מצולע באות; שיתוף האות (למשל S_{DEF} = S) קושר בין שני שטחים.' },
  { category: 'constraints', supported: true, en: 'perimeter of ABC = 20', he: 'היקף המשולש ABC = 20', descEn: 'A polygon\'s perimeter (Σ of its sides). A lone perimeter sets the figure\'s scale; with another given it shapes it. Also a ratio: "perimeter ABC = 2 perimeter DEF".', descHe: 'היקף של מצולע (סכום צלעותיו). היקף בודד קובע את גודל הסרטוט; עם נתון נוסף הוא קובע גם את הצורה. גם יחס: "היקף ABC = 2 היקף DEF".' },
  { category: 'constraints', supported: true, en: 'AB = 6', he: 'AB = 6', descEn: 'Fix a segment length (drives a sliding point, else checks).', descHe: 'קביעת אורך קטע (מזיז נקודה שיכולה לזוז, אחרת נבדק).' },
  { category: 'constraints', supported: true, en: 'AB = CD', he: 'AB = CD', descEn: 'Make two segments equal.', descHe: 'השוואת אורכי שני קטעים.' },
  { category: 'constraints', supported: true, en: 'AB = 2 AD', he: 'AB = 2 AD', descEn: 'A proportion between two lengths (|AB| = k·|CD|).', descHe: 'יחס בין שני אורכים (|AB| = k·|CD|).' },
  { category: 'constraints', supported: true, en: 'AB perpendicular to CD', he: 'AB מאונך ל-CD', descEn: 'Force a right angle between two segments.', descHe: 'אילוץ זווית ישרה בין שני קטעים.' },
  { category: 'constraints', supported: true, en: '△ABC ≅ △DEF', he: '△ABC ≅ △DEF', descEn: 'Congruent triangles (△, ≅ buttons; also "triangle ABC congruent to triangle DEF"). Reshapes the second to match the first (equal sides).', descHe: 'משולשים חופפים (כפתורים △, ≅; גם "משולש ABC חופף למשולש DEF"). מעצב את השני כך שיהיה חופף לראשון (צלעות שוות).' },
  { category: 'constraints', supported: true, en: '△ABC ~ △DEF', he: '△ABC ~ △DEF', descEn: 'Similar triangles (△, ~ buttons; also "triangle ABC similar to triangle DEF"). Reshapes the second to the same angles as the first.', descHe: 'משולשים דומים (כפתורים △, ~; גם "משולש ABC דומה למשולש DEF"). מעצב את השני לאותן זוויות כמו הראשון.' },
  { category: 'constraints', supported: true, en: 'AB = 3x', he: 'AB = 3x', descEn: 'A length as a variable (lowercase). Share it (e.g. DF = x) to set a relation; give it a value with "x = 4".', descHe: 'אורך כמשתנה (אות קטנה). שיתוף המשתנה (למשל DF = x) קובע יחס; ערך נקבע ע״י "x = 4".' },
  { category: 'constraints', supported: true, en: 'AD = 12√x', he: 'AD = 12√x', descEn: 'A length with a square root (√ button, or \\sqrt{x}). Symbolic until x gets a value (x = 4 ⇒ 24); 12√2 is a concrete length.', descHe: 'אורך עם שורש (כפתור √, או \\sqrt{x}). סימבולי עד שנקבע ערך ל-x (x = 4 ⇒ 24); 12√2 הוא אורך מספרי.' },
  { category: 'constraints', supported: true, en: 'AB = x²', he: 'AB = x²', descEn: 'A length raised to a power (x² button, or x^3). Resolves when x gets a value.', descHe: 'אורך בחזקה (כפתור x², או x^3). מתורגם למספר כשנקבע ערך ל-x.' },
  { category: 'constraints', supported: true, en: 'angle ABC = 2α', he: 'זווית ABC = 2α', descEn: 'An angle as a Greek variable. Share it (e.g. ∠DEF = α) for a relation; value via "α = 30".', descHe: 'זווית כמשתנה יווני. שיתוף המשתנה (למשל ∠DEF = α) קובע יחס; ערך ע״י "α = 30".' },
  { category: 'constraints', supported: true, en: 'α < β', he: 'α < β', descEn: 'An ordering between two named measures (< button). Reshapes the figure so the relation holds visibly (e.g. the angle labelled α comes out smaller).', descHe: 'יחס סדר בין שני מדדים בעלי שם (כפתור <). מעצב מחדש את הצורה כך שהיחס יתקיים באופן נראה (למשל הזווית שסומנה α תֵצא קטנה יותר).' },
  { category: 'constraints', supported: true, en: 'angle ABC is obtuse', he: 'זווית ABC קהה', descEn: 'Make an angle obtuse (>90°) — or acute (<90°) with "acute". Reshapes the figure so it holds; a single vertex ("∠C") works too.', descHe: 'הפיכת זווית לקהה (>90°) — או חדה (<90°) עם "חדה". מעצב מחדש את הצורה כך שיתקיים; אפשר גם קודקוד יחיד ("∠C").' },

  // ── Circles ─────────────────────────────────────────────────────────────
  { category: 'circles', supported: true, en: 'circle centered at O radius 5', he: 'מעגל סביב O רדיוס 5', descEn: 'A circle from a centre and radius.', descHe: 'מעגל לפי מרכז ורדיוס.' },
  { category: 'circles', supported: true, en: 'two circles with a common center O', he: 'שני מעגלים בעלי מרכז משותף O', descEn: 'Two concentric circles (both radii free). Refer to them as "the outer/inner circle"; size them with radius givens (e.g. OA=4 with A on one of them).', descHe: 'שני מעגלים קונצנטריים (שני הרדיוסים חופשיים). מתייחסים אליהם כ"המעגל החיצוני/הפנימי"; קובעים גודל בנתוני רדיוס (למשל OA=4 כאשר A על אחד מהם).' },
  { category: 'circles', supported: true, en: 'two circles', he: 'שני מעגלים', descEn: 'Two circles with NO stated relation — the mutual position (intersecting / disjoint / contained) is an open configuration "show another" toggles until more is given.', descHe: 'שני מעגלים ללא יחס מוצהר — המצב ההדדי (נחתכים / זרים / מוכלים) הוא תצורה פתוחה ש"הציגו תצורה אחרת" מחליפה עד שיינתן מידע נוסף.' },
  { category: 'circles', supported: true, en: 'two disjoint circles', he: 'שני מעגלים זרים', descEn: 'Two circles with no common point, each outside the other — kept disjoint by the figure (a requirement, not a drawing accident).', descHe: 'שני מעגלים ללא נקודה משותפת, זה מחוץ לזה — נשמרים זרים על ידי הדמות (דרישה, לא מקרה של הסרטוט).' },
  { category: 'circles', supported: true, en: 'circle P contained in circle O', he: 'מעגל P מוכל בתוך מעגל O', descEn: 'One circle strictly inside the other (also «שני מעגלים מוכלים» — the second is the inner by default). A requirement the sampler keeps.', descHe: 'מעגל אחד מוכל ממש בתוך האחר (גם «שני מעגלים מוכלים» — השני הוא הפנימי כברירת מחדל). דרישה שהדגימה שומרת.' },
  { category: 'circles', supported: true, en: 'AB is an external common tangent of the two circles', he: 'AB משיק משותף חיצוני לשני המעגלים', descEn: 'A common tangent with a stated KIND: external (centres on the same side) / internal, also «אלכסוני» (opposite sides). Label-less forms auto-name the touches; the plural («שני המשיקים המשותפים החיצוניים») draws both at once; a repeated one takes the other of its kind; «המשיקים נפגשים בנקודה K» then names the drawn tangents\' crossing (a contextual form — needs the tangents on the figure).', descHe: 'משיק משותף עם סוג מוצהר: חיצוני (המרכזים באותו צד) / פנימי או «אלכסוני» (בצדדים מנוגדים). צורות ללא אותיות ממנות נקודות השקה לבד; הרבים («שני המשיקים המשותפים») מסרטט את שניהם; משיק חוזר תופס את השני מסוגו; «המשיקים נפגשים בנקודה K» נותן שם לנקודת החיתוך של המשיקים המסורטטים (צורה תלוית-הקשר).' },
  { category: 'circles', supported: true, en: 'a line cuts the two circles at points C, D, E and F', he: 'ישר חותך את שני המעגלים בנקודות C, D, E ו-F', descEn: 'The textbook secant through both circles: the first two points on the first circle, the last two on the second, all four collinear in order.', descHe: 'החותך של שני המעגלים מהספר: שתי הנקודות הראשונות על המעגל הראשון, האחרונות על השני, ארבעתן על ישר אחד לפי הסדר.' },
  { category: 'circles', supported: true, en: 'circle O with circumference 6π', he: 'מעגל O שהיקפו 6π', descEn: 'A circle sized by its circumference (6π ⇒ radius 3). Its area works too: "circle O area 9π".', descHe: 'מעגל לפי היקפו (6π ⇐ רדיוס 3). גם לפי שטחו: "מעגל O ששטחו 9π".' },
  { category: 'circles', supported: true, en: 'circle with diameter 10', he: 'מעגל בקוטר 10', descEn: 'A circle sized by its diameter (10 ⇒ radius 5).', descHe: 'מעגל לפי קוטרו (10 ⇐ רדיוס 5).' },
  { category: 'circles', supported: true, en: 'circle O with radius R', he: 'מעגל O שרדיוסו R', descEn: 'Names the radius with a LETTER (the size stays free). Each circle can bind its own letter ("circle P with radius r", or after the fact: "radius of circle P is r"); relations between the letters then work: "R > r", "R = 1.5r", "R/r = 2√7/5", and lengths like "AB = √2R". With two circles you can also refer to them as "the big/small circle" — the first use fixes which is which (and keeps it).', descHe: 'נותן לרדיוס שם-אות (הגודל נשאר חופשי). לכל מעגל אות משלו ("מעגל P שרדיוסו r", או בדיעבד: "רדיוס מעגל P הוא r"); ואז עובדים יחסים בין האותיות: "R > r", "R = 1.5r", "R/r = 2√7/5", ואורכים כמו "AB = √2R". עם שני מעגלים אפשר גם להתייחס אליהם כ"המעגל הגדול/הקטן" — ההתייחסות הראשונה קובעת מי הגדול (ונשמרת).' },
  { category: 'circles', supported: true, en: 'A is on circle O', he: 'A על מעגל O', descEn: 'A point on a circle / inscribed vertex.', descHe: 'נקודה על מעגל / קודקוד חסום.' },
  { category: 'circles', supported: true, en: 'M is outside circle O', he: 'M מחוץ למעגל O', descEn: 'A point outside a circle (a free point kept strictly outside; with one circle "M is outside the circle" works; "inside" too — "M inside circle O").', descHe: 'נקודה מחוץ למעגל (נקודה חופשית שנשארת מחוץ למעגל; כשיש מעגל אחד אפשר "M מחוץ למעגל"; גם "בתוך" — "M בתוך מעגל O").' },
  { category: 'circles', supported: true, en: 'O is the centre of the circle', he: 'O מרכז המעגל', descEn: "Name / reveal a circle's centre O (reveals an existing circle's hidden centre, or creates a circle if none exists yet).", descHe: 'מתן שם / חשיפת מרכז המעגל O (חושף מרכז מוסתר של מעגל קיים, או יוצר מעגל אם עדיין אין).' },
  { category: 'circles', supported: true, en: 'triangle ABC inscribed in circle O', he: 'משולש ABC חסום במעגל O', descEn: 'A triangle with all vertices on a circle.', descHe: 'משולש שכל קודקודיו על מעגל.' },
  { category: 'circles', supported: true, en: 'right triangle ABC inscribed in a circle', he: 'משולש ישר-זווית ABC חסום במעגל', descEn: 'A right triangle inscribed (hypotenuse is a diameter).', descHe: 'משולש ישר-זווית חסום (היתר הוא קוטר).' },
  { category: 'circles', supported: true, en: 'circle through A B C', he: 'מעגל חוסם את ABC', descEn: 'The circle through three points (circumscribed).', descHe: 'המעגל החוסם שלושה קודקודים.' },
  { category: 'circles', supported: true, en: 'the circle through A B C cuts CE at D', he: 'המעגל החוסם את משולש ABC חותך את CE בנקודה D', descEn: 'The circumcircle of a triangle ∩ a segment (the crossing other than the shared vertex).', descHe: 'המעגל החוסם משולש החותך קטע (החיתוך שאינו הקודקוד המשותף).' },
  { category: 'circles', supported: true, en: 'circle inscribed in triangle ABC', he: 'מעגל חסום במשולש ABC', descEn: 'The incircle — tangent to the three sides (centred at the incenter).', descHe: 'המעגל החסום — משיק לשלוש הצלעות (מרכזו מפגש חוצי הזוויות).' },
  { category: 'circles', supported: true, en: 'triangle DEF circumscribes the circle', he: 'משולש DEF חוסם את המעגל', descEn: 'The triangle encloses a circle tangent to its three sides (the incircle, triangle-first phrasing).', descHe: 'המשולש חוסם מעגל המשיק לשלוש צלעותיו (המעגל החסום, בניסוח שמתחיל במשולש).' },
  { category: 'circles', supported: true, en: 'circle inscribed in trapezoid ABCD', he: 'מעגל חסום בטרפז ABCD', descEn: 'The incircle of a quad / trapezoid — the shape flexes to be tangential, so all four sides touch the circle.', descHe: 'המעגל החסום במרובע / טרפז — הצורה מתגמשת כך שכל ארבע הצלעות משיקות למעגל.' },
  { category: 'circles', supported: true, en: 'in quadrilateral ABCD a circle is inscribed', he: 'במרובע ABCD חסום מעגל O', descEn: 'The container-first (inverted passive) phrasing of the incircle — the noun carrying "in" is the container, wherever it sits in the sentence.', descHe: 'הניסוח ההפוך של המעגל החסום — הצורה הנושאת את אות היחס ב׳ היא המכילה, בכל מיקום במשפט.' },
  { category: 'circles', supported: true, en: 'circle inscribed in kite ABCD', he: 'מעגל חסום בדלתון ABCD', descEn: 'The incircle of a kite — every kite is tangential, so all four sides touch it.', descHe: 'המעגל החסום בדלתון — כל דלתון משיק, ולכן כל ארבע צלעותיו נוגעות במעגל.' },
  { category: 'circles', supported: true, en: 'the tangent at A and the tangent at C to circle O meet at D', he: 'המשיק בנקודה A והמשיק בנקודה C למעגל O נפגשים בנקודה D', descEn: 'Two tangents at points on the circle meet at a point (the pole of chord AC).', descHe: 'שני משיקים בנקודות שעל המעגל נפגשים בנקודה (הקוטב של המיתר AC).' },
  { category: 'circles', supported: true, en: 'AB and AD are tangent to circle O at E and K', he: 'AB ו-AD משיקים למעגל O בנקודות E ו-K', descEn: 'A circle tangent to two sides meeting at a corner (centre on the angle bisector; its size is a free DOF).', descHe: 'מעגל המשיק לשתי צלעות הנפגשות בקודקוד (מרכזו על חוצה הזווית; גודלו דרגת חופש).' },
  { category: 'circles', supported: true, en: 'trapezoid ABCD inscribed in a circle', he: 'טרפז ABCD חסום במעגל', descEn: 'A cyclic (isosceles) trapezoid — also square/rectangle/rhombus/kite.', descHe: 'טרפז חסום (שווה-שוקיים) — וכן ריבוע/מלבן/מעוין/דלתון.' },
  { category: 'circles', supported: true, en: 'cyclic quadrilateral ABCD', he: 'מרובע ABCD בר חסימה', descEn: 'A quadrilateral whose vertices are concyclic (opposite angles sum to 180°) — the circle is not drawn.', descHe: 'מרובע בר חסימה — קודקודיו על מעגל (סכום זוויות נגדיות 180°), והמעגל עצמו אינו מצויר.' },
  { category: 'circles', supported: true, en: 'semicircle with diameter AB', he: 'חצי מעגל שקוטרו AB', descEn: 'A half circle: a 180° arc on the diameter AB (the diameter is drawn).', descHe: 'חצי מעגל: קשת של 180° על הקוטר AB (הקוטר מצויר).' },
  { category: 'circles', supported: true, en: 'a semicircle on each side of square ABCD', he: 'על כל צלע של ריבוע ABCD יש חצי מעגל', descEn: 'A semicircle erected on every side of a polygon (the classic composite figure).', descHe: 'חצי מעגל על כל צלע של מצולע (הצורה המורכבת הקלאסית).' },
  { category: 'circles', supported: true, en: 'semicircle on side AB outside triangle ABC', he: 'חצי מעגל על צלע AB מחוץ למשולש ABC', descEn: 'A semicircle erected on a polygon side, bulging outside (or "inside") the shape.', descHe: 'חצי מעגל על צלע של מצולע, בולט החוצה (או "בתוך") מהצורה.' },
  { category: 'circles', supported: true, en: 'quarter circle', he: 'רבע מעגל', descEn: 'A 90° arc with its two bounding radii.', descHe: 'קשת של 90° עם שני הרדיוסים התוחמים אותה.' },
  { category: 'circles', supported: true, en: 'sector AOB with angle 80', he: 'גזרה AOB בזווית 80', descEn: 'A circular sector: an arc + its two bounding radii. Without a stated angle the central angle is a free DOF ("show another" varies it); the value also reads as "equals 80" / "= 80" / "80°"; a reflex angle (e.g. 200) draws the major arc. Letters read like an angle — the centre in the MIDDLE (AOB); an O-family centre letter is the centre wherever it sits (OAB works too).', descHe: 'גזרה: קשת + שני הרדיוסים התוחמים. ללא זווית נתונה הזווית המרכזית חופשית ("הציגו תצורה אחרת" משנה אותה); הזווית נקראת גם בצורות "שווה 80" / "= 80" / "80°"; זווית מעל 180 (למשל 200) מציירת את הקשת הגדולה. האותיות נקראות כמו זווית — המרכז באמצע (AOB); אות מרכז ממשפחת O היא המרכז בכל מיקום (גם OAB).' },
  { category: 'circles', supported: true, en: 'chord AB in circle O', he: 'מיתר AB במעגל O', descEn: 'A chord of a circle (both ends on it).', descHe: 'מיתר במעגל (שני קצותיו עליו).' },
  { category: 'circles', supported: true, en: 'AB and CD are chords in circle O', he: 'AB ו-CD מיתרים במעגל O', descEn: 'Several chords declared at once — every pair is a chord (issue #151).', descHe: 'כמה מיתרים בהצהרה אחת — כל זוג הוא מיתר.' },
  { category: 'circles', supported: true, en: 'from a point E outside circle O a line cuts the circle at A and B', he: 'מנקודה E מחוץ למעגל O ישר חותך את המעגל בנקודות A ו-B', descEn: 'A secant from an external point: A,B on the circle, E outside, collinear.', descHe: 'חותך מנקודה חיצונית: A,B על המעגל, E מחוץ, על ישר אחד.' },
  { category: 'circles', supported: true, en: 'the line AO cuts circle O at C and D', he: 'הישר AO חותך את מעגל O בנקודות C ו-D', descEn: 'A named line crossing the circle at BOTH points (e.g. a secant through the centre).', descHe: 'ישר נתון (לפי שתי נקודות) החותך את המעגל בשתי הנקודות (למשל חותך העובר דרך המרכז).' },
  { category: 'circles', supported: true, en: 'AD cuts circle O at B', he: 'AD חותך את מעגל O בנקודה B', descEn: 'A secant from external apex A: B the near crossing, D the far one (a new point on the circle). Leave the near crossing unnamed («AD cuts circle O») and the secant’s rotation is free; add «through P» to pin it.', descHe: 'חותך מקודקוד חיצוני A: B החיתוך הקרוב, D הרחוק (נקודה חדשה על המעגל). אפשר להשאיר את הקרוב ללא שם («AD חותך למעגל») וסיבוב החותך חופשי; «דרך P» מקבע אותו.' },
  { category: 'circles', supported: true, en: 'from point E outside circle O two tangents touch the circle at A and B', he: 'מנקודה E מחוץ למעגל O שני משיקים נוגעים במעגל בנקודות A ו-B', descEn: 'The two tangents from an external point, touching at A and B (EA⟂OA, EB⟂OB).', descHe: 'שני המשיקים מנקודה חיצונית, נוגעים ב-A ו-B (EA⟂OA, EB⟂OB).' },
  { category: 'circles', supported: true, en: 'from point E a tangent touches circle O at D', he: 'מנקודה E משיק נוגע במעגל O בנקודה D', descEn: 'A single tangent from an external point, touching at D (ED⟂OD).', descHe: 'משיק יחיד מנקודה חיצונית, נוגע ב-D (ED⟂OD).' },
  { category: 'circles', supported: true, en: 'diameter AB in circle O', he: 'קוטר AB במעגל O', descEn: 'A chord through the centre.', descHe: 'מיתר העובר במרכז.' },
  { category: 'circles', supported: true, en: 'the diameter of circle O from F cuts side AC at E', he: 'קוטר מעגל O היוצא מנקודה F חותך את הצלע AC בנקודה E', descEn: 'The diameter through an on-circle point meets a side at E; E stays on the segment (the figure flexes).', descHe: 'הקוטר היוצא מנקודה שעל המעגל פוגש צלע בנקודה E; E נשארת על הקטע (הצורה מסתגלת).' },
  { category: 'circles', supported: true, en: 'diameter from F in circle O', he: 'קוטר מנקודה F במעגל O', descEn: 'The diameter drawn from an on-circle point; the far end (the antipode) is auto-named.', descHe: 'הקוטר היוצא מנקודה שעל המעגל; הקצה הרחוק (הנקודה הנגדית) מקבל שם אוטומטית.' },
  { category: 'circles', supported: true, en: 'diameter through A in circle O', he: 'קוטר העובר בנקודה A במעגל O', descEn: 'The same diameter, phrased as passing THROUGH the point (also "בנקודה A", "דרך A", a leading "add/הוסף").', descHe: 'אותו קוטר, בניסוח "עובר דרך" (גם «בנקודה A», «דרך A», ופתיח «הוסף»).' },
  { category: 'circles', supported: true, en: 'M is the midpoint of arc BC in circle O', he: 'M אמצע הקשת BC במעגל O', descEn: 'The midpoint of an arc.', descHe: 'אמצע הקשת.' },
  { category: 'circles', supported: true, en: 'tangent to circle O at A', he: 'משיק למעגל O בנקודה A', descEn: 'Draw the tangent at a point on a circle.', descHe: 'ציור המשיק בנקודה על המעגל.' },
  { category: 'circles', supported: true, en: 'E is the intersection of the tangent to circle O at A and BC', he: 'E חיתוך המשיק למעגל O בנקודה A עם BC', descEn: 'Where a tangent at a point meets a line.', descHe: 'מפגש משיק בנקודה עם ישר.' },
  { category: 'circles', supported: true, en: 'G is the intersection of circle O and circle P', he: 'G חיתוך מעגל O ומעגל P', descEn: 'Where two circles cross.', descHe: 'נקודת חיתוך של שני מעגלים.' },
  { category: 'circles', supported: true, en: 'two circles intersect at A and B', he: 'שני מעגלים נחתכים בנקודות A ו-B', descEn: 'Two overlapping circles and both intersection points A, B. Refer to them as "the right/left circle" («המעגל הימני/השמאלי»), or name a centre: «מרכז המעגל הימני הוא O1».', descHe: 'שני מעגלים נחתכים ושתי נקודות החיתוך A, B. מתייחסים אליהם כ"המעגל הימני/השמאלי", או נותנים שם למרכז: «מרכז המעגל הימני הוא O1».' },
  { category: 'circles', supported: true, en: 'the tangent to circle O at A meets circle P at D', he: 'המשיק למעגל O בנקודה A חותך את מעגל P בנקודה D', descEn: 'A tangent to one circle (at a point on it) crossing the other circle at a new point.', descHe: 'משיק למעגל אחד (בנקודה שעליו) החותך את המעגל האחר בנקודה חדשה.' },
  { category: 'circles', supported: true, en: 'AC extended meets circle P at E', he: 'המשך AC חותך את מעגל P בנקודה E', descEn: 'A DIRECTIONAL extension: E is beyond the 2nd letter (order A→C→E) on circle P; a free-radius circle adapts so the extension reaches it.', descHe: 'המשך מכוון: E מעבר לאות השנייה (סדר A→C→E) על מעגל P; מעגל עם רדיוס חופשי מסתגל כדי שההמשך יגיע אליו.' },
  { category: 'circles', supported: true, en: 'line AC meets circle P at E', he: 'הישר AC פוגש את מעגל P בנקודה E', descEn: 'An order-agnostic chord: line AC crosses circle P at E (the crossing other than a shared on-circle end).', descHe: 'מיתר ללא תלות בסדר: הישר AC חותך את מעגל P בנקודה E (החיתוך שאינו הקצה המשותף שעל המעגל).' },
  { category: 'circles', supported: true, en: 'circle O and circle P are tangent at M', he: 'מעגל O ומעגל P משיקים זה לזה בנקודה M', descEn: 'Two circles touching externally at one point M (side by side; the centres move to touch).', descHe: 'שני מעגלים משיקים זה לזה מבחוץ בנקודה אחת M (זה ליד זה; המרכזים זזים כדי להשיק).' },
  { category: 'circles', supported: true, en: 'circle O and circle P are tangent internally at M', he: 'מעגל O ומעגל P משיקים מבפנים בנקודה M', descEn: 'One circle inside the other, touching at M (needs different radii).', descHe: 'מעגל אחד בתוך השני, משיקים בנקודה M (דרושים רדיוסים שונים).' },
  { category: 'circles', supported: true, en: 'AB is a common tangent to circles O and P', he: 'AB משיק משותף למעגלים O ו-P', descEn: 'A common tangent of two circles, touching circle O at A and circle P at B (radius ⟂ tangent at each touch). With two circles on the figure, "לשני המעגלים"/"the two circles" also works.', descHe: 'משיק משותף לשני מעגלים, נוגע במעגל O ב-A ובמעגל P ב-B (רדיוס ⟂ משיק בכל השקה). כששני מעגלים כבר בציור אפשר גם "לשני המעגלים".' },
<<<<<<< HEAD
  { category: 'circles', supported: true, en: 'CD is a common tangent to circles O and P at M', he: 'CD משיק משותף למעגלים O ו-P בנקודה M', descEn: 'The common tangent at the shared touch point M of two tangent circles (drawn ⟂ to the line of centres).', descHe: 'המשיק המשותף בנקודת ההשקה M של שני מעגלים משיקים (מצויר ⟂ לקו המרכזים).' },
  // ── #184: the unnamed-construct family (auto-named — the student needn't supply a letter) ──
  { category: 'points', supported: true, en: 'midpoint of AB', he: 'אמצע AB', descEn: 'The midpoint of a segment, auto-named (also «הוסף אמצע צלע AB»).', descHe: 'אמצע קטע, בשם אוטומטי (גם «הוסף אמצע צלע AB»).' },
  { category: 'circles', supported: true, en: 'a tangent to the circle', he: 'משיק למעגל', descEn: 'A tangent line to the circle at an auto-named free touch point.', descHe: 'משיק למעגל בנקודת השקה חופשית בשם אוטומטי.' },
  { category: 'circles', supported: true, en: 'a diameter', he: 'קוטר', descEn: 'A diameter of the circle, both endpoints auto-named.', descHe: 'קוטר של המעגל, שני הקצוות בשם אוטומטי.' },
  { category: 'circles', supported: true, en: 'a line cutting the circle at two points', he: 'ישר החותך את המעגל בשתי נקודות', descEn: 'A secant through two auto-named points on the circle (naming them works too: «בנקודות C ו-D»).', descHe: 'ישר החותך את המעגל בשתי נקודות בשם אוטומטי (אפשר גם לנקוב בשמות: «בנקודות C ו-D»).' },
  { category: 'circles', supported: true, en: 'given a circle', he: 'נתון מעגל', descEn: 'A bare circle request wrapped in a given-marker.', descHe: 'בקשת מעגל עם מילת נתון.' },
  { category: 'circles', supported: true, en: 'circle with center O', he: 'מעגל עם מרכז O', descEn: 'A circle by its named centre — the «עם מרכז» phrasing.', descHe: 'מעגל לפי מרכז בשמו — הניסוח «עם מרכז».' },
  { category: 'circles', supported: true, en: 'the centre of the circle', he: 'מרכז המעגל', descEn: 'Reveal the circle’s hidden centre (auto-named by its own letter).', descHe: 'חשיפת מרכז המעגל החבוי (בשמו האוטומטי).' },
  { category: 'circles', supported: true, en: 'AB tangent to circle C', he: 'AB משיק למעגל C', descEn: 'A segment tangent to a circle with NO touch point named: on existing A,B it constrains the circle (the touch is the ⟂ foot from the centre, kept within AB); on new A,B it draws the tangent with A,B as markers.', descHe: 'קטע משיק למעגל בלי לנקוב בנקודת ההשקה: על A,B קיימות זהו אילוץ על המעגל (ההשקה היא רגל האנך מהמרכז, בתוך AB); על A,B חדשות מצויר המשיק ו-A,B סימונים עליו.' },
  { category: 'circles', supported: true, en: 'from point A two tangents to both circles', he: 'מנקודה A יוצאים שני משיקים לשני המעגלים', descEn: 'The two common tangents drawn from an external point A — A lies on each tangent line beyond its touches (the classic two-circle bagrut figure; singular «משיק» draws one).', descHe: 'שני המשיקים המשותפים מנקודה חיצונית A — A על כל משיק מעבר לנקודות ההשקה (הציור הקלאסי של שני מעגלים בבגרות; «משיק» ביחיד מצייר אחד).' },
=======
  { category: 'circles', supported: true, en: 'AB tangent to circle C', he: 'AB משיק למעגל C', descEn: 'A segment tangent to a circle with NO touch point named: on existing A,B it constrains the circle (the touch is the ⟂ foot from the centre, kept within AB); on new A,B it draws the tangent with A,B as markers.', descHe: 'קטע משיק למעגל בלי לנקוב בנקודת ההשקה: על A,B קיימות זהו אילוץ על המעגל (ההשקה היא רגל האנך מהמרכז, בתוך AB); על A,B חדשות מצויר המשיק ו-A,B סימונים עליו.' },
>>>>>>> feat/203-segment-tangency-no-touch
];
